version: '3.8'

services:

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./api/test/mongodb/:/docker-entrypoint-initdb.d/
